// All icons from @tabler/icons-react — tree-shakeable, consistent stroke style
export {
  IconSearch,
  IconArrowRight,
  IconArrowLeft,
  IconStar,
  IconEye,
  IconTag,
  IconBulb,
  IconFlask,
  IconLock,
  IconHeart,
  IconGlobe,
  IconClock,
  IconBug,
  IconBook,
  IconRocket,
  IconFlame,
  IconAward,
  IconTrophy,
  IconCheck,
  IconRoute,
  IconUser,
  IconDeviceLaptop,
  IconLayoutGrid,
  IconShare,
  // Git
  IconGitBranch as IconBranch,
  IconGitPullRequest as IconPR,
  IconGitMerge,
  IconGitFork as IconFork,
  // Brands
  IconBrandGithub as IconGithub,
  IconBrandDiscordFilled as IconDiscord,
} from "@tabler/icons-react"
