import type { DiffFile } from "@/features/playground/domain/diff"

export const codeReviewNoisyPrDiff: readonly DiffFile[] = [
  {
    filename: "src/gateway/request.ts",
    additions: 22,
    deletions: 13,
    lines: [
      { type: "hunk", content: "@@ -1,18 +1,31 @@" },
      { type: "context", content: 'import type { RequestOptions } from "./types"' },
      { type: "context", content: "" },
      { type: "removed", content: "export async function fetchUpstream(" },
      { type: "removed", content: "  url: string," },
      { type: "removed", content: "  options: RequestOptions = {}" },
      { type: "removed", content: "): Promise<Response> {" },
      { type: "removed", content: "  const response = await fetch(url, {" },
      { type: "removed", content: "    headers: options.headers," },
      { type: "removed", content: '    method: options.method ?? "GET",' },
      { type: "removed", content: "  })" },
      { type: "removed", content: "  if (!response.ok) {" },
      { type: "removed", content: "    throw new Error(`HTTP ${response.status}: ${url}`)" },
      { type: "removed", content: "  }" },
      { type: "removed", content: "  return response" },
      { type: "removed", content: "}" },
      { type: "added", content: "export async function fetchUpstream(" },
      { type: "added", content: "  url: string," },
      { type: "added", content: "  options: RequestOptions = {}" },
      { type: "added", content: "): Promise<Response | null> {" },
      { type: "added", content: "  const controller = new AbortController()" },
      {
        type: "added",
        content:
          "  const timeoutId = setTimeout(() => controller.abort(), options.timeout ?? 5000)",
      },
      {
        type: "added",
        content: "  console.log(`[debug] fetchUpstream called: ${url}`)",
      },
      { type: "added", content: "  try {" },
      { type: "added", content: "    const response = await fetch(url, {" },
      { type: "added", content: "      headers: options.headers," },
      { type: "added", content: '      method: options.method ?? "GET",' },
      { type: "added", content: "      signal: controller.signal," },
      { type: "added", content: "    })" },
      { type: "added", content: "    if (!response.ok) {" },
      { type: "added", content: "      throw new Error(`HTTP ${response.status}: ${url}`)" },
      { type: "added", content: "    }" },
      { type: "added", content: "    return response" },
      { type: "added", content: "  } catch (err) {" },
      { type: "added", content: '    if (err instanceof Error && err.name === "AbortError") {' },
      { type: "added", content: "      return null" },
      { type: "added", content: "    }" },
      { type: "added", content: "    throw err" },
      { type: "added", content: "  } finally {" },
      { type: "added", content: "    clearTimeout(timeoutId)" },
      { type: "added", content: "  }" },
      { type: "context", content: "}" },
    ],
  },
  {
    filename: "src/gateway/types.ts",
    additions: 1,
    deletions: 0,
    lines: [
      { type: "hunk", content: "@@ -1,5 +1,6 @@" },
      { type: "context", content: "export type RequestOptions = {" },
      { type: "context", content: "  headers?: Record<string, string>" },
      { type: "context", content: "  method?: string" },
      { type: "added", content: "  timeout?: number" },
      { type: "context", content: "}" },
    ],
  },
  {
    filename: "src/gateway/retry.ts",
    additions: 5,
    deletions: 8,
    lines: [
      { type: "hunk", content: "@@ -1,20 +1,17 @@" },
      { type: "removed", content: 'import { fetchUpstream } from "./request"' },
      { type: "removed", content: 'import type { RequestOptions } from "./types"' },
      { type: "added", content: 'import type { RequestOptions } from "./types"' },
      { type: "added", content: 'import { fetchUpstream } from "./request"' },
      { type: "context", content: "" },
      { type: "removed", content: "const DEFAULT_RETRIES = 3" },
      { type: "added", content: "const DEFAULT_RETRIES = 3 as const" },
      { type: "context", content: "" },
      { type: "context", content: "export async function withRetry(" },
      { type: "context", content: "  url: string," },
      { type: "context", content: "  options: RequestOptions = {}," },
      { type: "context", content: "  retries = DEFAULT_RETRIES" },
      { type: "context", content: "): Promise<Response> {" },
      { type: "hunk", content: "@@ -8,10 +8,7 @@" },
      { type: "removed", content: "  for (let i = 0; i < retries; i++) {" },
      { type: "added", content: "  for (let attempt = 0; attempt < retries; attempt++) {" },
      { type: "context", content: "    try {" },
      { type: "context", content: "      return await fetchUpstream(url, options)" },
      { type: "context", content: "    } catch (err) {" },
      { type: "removed", content: "      if (i === retries - 1) throw err" },
      { type: "removed", content: "      const delay = 2 ** i * 100" },
      { type: "removed", content: "      await new Promise((r) => setTimeout(r, delay))" },
      { type: "added", content: "      if (attempt === retries - 1) throw err" },
      {
        type: "added",
        content: "      await new Promise((r) => setTimeout(r, 2 ** attempt * 100))",
      },
      { type: "context", content: "    }" },
      { type: "context", content: "  }" },
      { type: "removed", content: '  throw new Error("withRetry: exhausted all retries")' },
      { type: "added", content: '  throw new Error("Exhausted all retries")' },
      { type: "context", content: "}" },
    ],
  },
  {
    filename: "src/gateway/index.ts",
    additions: 1,
    deletions: 0,
    lines: [
      { type: "hunk", content: "@@ -1,3 +1,4 @@" },
      { type: "context", content: 'export { fetchUpstream } from "./request"' },
      { type: "context", content: 'export { withRetry } from "./retry"' },
      { type: "added", content: 'export type { RequestOptions } from "./types"' },
    ],
  },
]
