/**
 * Regenerates the challenges catalog from content/playground frontmatter.
 *
 * Reads category and difficulty from every challenge MDX (Spanish variant —
 * both languages share the same values), maps difficulty to points, and
 * writes a `*_sync_challenges.sql` migration that upserts the catalog and
 * deactivates removed challenges. Apply it with `bunx supabase db push`.
 *
 * Usage: bun run db:sync-challenges
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"

const CONTENT_DIR = join(process.cwd(), "content", "playground")
const MIGRATIONS_DIR = join(process.cwd(), "supabase", "migrations")

const POINTS_BY_DIFFICULTY: Readonly<Record<string, number>> = {
  beginner: 10,
  moderate: 20,
  demanding: 30,
}

type ChallengeMeta = {
  readonly slug: string
  readonly category: string
  readonly difficulty: string
  readonly points: number
}

const readFrontmatterField = (source: string, field: string): string | null => {
  const match = new RegExp(`^${field}:\\s*(.+)$`, "m").exec(source)
  const value = match?.[1]
  return value === undefined ? null : value.trim().replace(/^"(.*)"$/, "$1")
}

const collectChallenges = (): readonly ChallengeMeta[] =>
  readdirSync(CONTENT_DIR)
    .filter((file) => file.endsWith(".es.mdx"))
    .map((file): ChallengeMeta => {
      const slug = file.replace(/\.es\.mdx$/, "")
      const source = readFileSync(join(CONTENT_DIR, file), "utf8")
      const category = readFrontmatterField(source, "category")
      const difficulty = readFrontmatterField(source, "difficulty")

      if (category === null || difficulty === null) {
        throw new Error(`${file}: missing category or difficulty in frontmatter`)
      }

      const points = POINTS_BY_DIFFICULTY[difficulty]
      if (points === undefined) {
        throw new Error(`${file}: unknown difficulty "${difficulty}"`)
      }

      return { slug, category, difficulty, points }
    })
    .toSorted((first, second) => first.slug.localeCompare(second.slug))

const buildMigrationSql = (challenges: readonly ChallengeMeta[]): string => {
  const valueRows = challenges
    .map(
      ({ slug, category, difficulty, points }) =>
        `  ('${slug}', '${category}', '${difficulty}', ${points})`
    )
    .join(",\n")
  const activeSlugs = challenges.map(({ slug }) => `'${slug}'`).join(", ")

  return `-- Generated by scripts/sync-challenges.ts — do not edit by hand.
-- Syncs the challenges catalog with content/playground frontmatter.

insert into public.challenges (slug, category, difficulty, points) values
${valueRows}
on conflict (slug) do update set
  category = excluded.category,
  difficulty = excluded.difficulty,
  points = excluded.points,
  active = true;

update public.challenges set active = false where slug not in (${activeSlugs});
`
}

const migrationTimestamp = (): string => new Date().toISOString().replace(/\D/g, "").slice(0, 14)

const run = (): void => {
  const challenges = collectChallenges()
  const migrationPath = join(MIGRATIONS_DIR, `${migrationTimestamp()}_sync_challenges.sql`)

  writeFileSync(migrationPath, buildMigrationSql(challenges))
  console.log(`Wrote ${migrationPath} (${challenges.length} challenges).`)
  console.log("Review it, then apply with: bunx supabase db push")
}

run()
